define([], function(){
    /**
        Returns a description of all MUFI 3.0 chars as taken from [1],
        where PUA hasn't been used, but the symbols are in Unicode.
        The description is a mapping from code chart names to maps from code points to their descriptions.
        The code chart names are preserved to allow deducing where something comes from.
        Notice that [1] contains the code chart as its range parameter,
        which may be useful for future updates to this file.
        [1]: http://www.abdn.ac.uk/skaldic/db.php?if=mufi&range=AlphPresForm&table=mufi_char
    */
    return {
        "AlphPresForm": {   "FB00": "LATIN SMALL LIGATURE FF"
                        ,   "FB01": "LATIN SMALL LIGATURE FI"
                        ,   "FB02": "LATIN SMALL LIGATURE FL"
                        ,   "FB05": "LATIN SMALL LIGATURE LONG S T"
                        ,   "FB06": "LATIN SMALL LIGATURE ST"}
    ,   "AncSymb": {   "FB00": "LATIN SMALL LIGATURE FF"
                   ,   "FB01": "LATIN SMALL LIGATURE FI"
                   ,   "FB02": "LATIN SMALL LIGATURE FL"
                   ,   "FB05": "LATIN SMALL LIGATURE LONG S T"
                   ,   "FB06": "LATIN SMALL LIGATURE ST"}
    ,   "Arrows": {   "2190": "LEFTWARDS ARROW"
                  ,   "2191": "UPWARDS ARROW"
                  ,   "2192": "RIGHTWARDS ARROW"
                  ,   "2193": "DOWNWARDS ARROW" }
    ,   "BasLat": {   "0020": "SPACE"
                  ,   "0021": "EXCLAMATION MARK"
                  ,   "0022": "QUOTATION MARK"
                  ,   "0023": "NUMBER SIGN"
                  ,   "0024": "DOLLAR SIGN"
                  ,   "0025": "PERCENT SIGN"
                  ,   "0026": "AMPERSAND"
                  ,   "0027": "APOSTROPHE"
                  ,   "0028": "LEFT PARENTHESIS"
                  ,   "0029": "RIGHT PARENTHESIS"
                  ,   "002A": "ASTERISK"
                  ,   "002B": "PLUS SIGN"
                  ,   "002C": "COMMA"
                  ,   "002D": "HYPHEN-MINUS"
                  ,   "002E": "FULL STOP"
                  ,   "002F": "SOLIDUS"
                  ,   "0030": "DIGIT ZERO"
                  ,   "0031": "DIGIT ONE"
                  ,   "0032": "DIGIT TWO"
                  ,   "0033": "DIGIT THREE"
                  ,   "0034": "DIGIT FOUR"
                  ,   "0035": "DIGIT FIVE"
                  ,   "0036": "DIGIT SIX"
                  ,   "0037": "DIGIT SEVEN"
                  ,   "0038": "DIGIT EIGHT"
                  ,   "0039": "DIGIT NINE"
                  ,   "003A": "COLON"
                  ,   "003B": "SEMICOLON"
                  ,   "003C": "LESS-THAN SIGN"
                  ,   "003D": "EQUALS SIGN"
                  ,   "003E": "GREATER-THAN SIGN"
                  ,   "003F": "QUESTION MARK"
                  ,   "0040": "COMMERCIAL AT"
                  ,   "0041": "LATIN CAPITAL LETTER A"
                  ,   "0042": "LATIN CAPITAL LETTER B"
                  ,   "0043": "LATIN CAPITAL LETTER C"
                  ,   "0044": "LATIN CAPITAL LETTER D"
                  ,   "0045": "LATIN CAPITAL LETTER E"
                  ,   "0046": "LATIN CAPITAL LETTER F"
                  ,   "0047": "LATIN CAPITAL LETTER G"
                  ,   "0048": "LATIN CAPITAL LETTER H"
                  ,   "0049": "LATIN CAPITAL LETTER I"
                  ,   "004A": "LATIN CAPITAL LETTER J"
                  ,   "004B": "LATIN CAPITAL LETTER K"
                  ,   "004C": "LATIN CAPITAL LETTER L"
                  ,   "004D": "LATIN CAPITAL LETTER M"
                  ,   "004E": "LATIN CAPITAL LETTER N"
                  ,   "004F": "LATIN CAPITAL LETTER O"
                  ,   "0050": "LATIN CAPITAL LETTER P"
                  ,   "0051": "LATIN CAPITAL LETTER Q"
                  ,   "0052": "LATIN CAPITAL LETTER R"
                  ,   "0053": "LATIN CAPITAL LETTER S"
                  ,   "0054": "LATIN CAPITAL LETTER T"
                  ,   "0055": "LATIN CAPITAL LETTER U"
                  ,   "0056": "LATIN CAPITAL LETTER V"
                  ,   "0057": "LATIN CAPITAL LETTER W"
                  ,   "0058": "LATIN CAPITAL LETTER X"
                  ,   "0059": "LATIN CAPITAL LETTER Y"
                  ,   "005A": "LATIN CAPITAL LETTER Z"
                  ,   "005B": "LEFT SQUARE BRACKET"
                  ,   "005C": "REVERSE SOLIDUS"
                  ,   "005D": "RIGHT SQUARE BRACKET"
                  ,   "005E": "CIRCUMFLEX ACCENT"
                  ,   "005F": "LOW LINE"
                  ,   "0060": "GRAVE ACCENT"
                  ,   "0061": "LATIN SMALL LETTER A"
                  ,   "0062": "LATIN SMALL LETTER B"
                  ,   "0063": "LATIN SMALL LETTER C"
                  ,   "0064": "LATIN SMALL LETTER D"
                  ,   "0065": "LATIN SMALL LETTER E"
                  ,   "0066": "LATIN SMALL LETTER F"
                  ,   "0067": "LATIN SMALL LETTER G"
                  ,   "0068": "LATIN SMALL LETTER H"
                  ,   "0069": "LATIN SMALL LETTER I"
                  ,   "006A": "LATIN SMALL LETTER J"
                  ,   "006B": "LATIN SMALL LETTER K"
                  ,   "006C": "LATIN SMALL LETTER L"
                  ,   "006D": "LATIN SMALL LETTER M"
                  ,   "006E": "LATIN SMALL LETTER N"
                  ,   "006F": "LATIN SMALL LETTER O"
                  ,   "0070": "LATIN SMALL LETTER P"
                  ,   "0071": "LATIN SMALL LETTER Q"
                  ,   "0072": "LATIN SMALL LETTER R"
                  ,   "0073": "LATIN SMALL LETTER S"
                  ,   "0074": "LATIN SMALL LETTER T"
                  ,   "0075": "LATIN SMALL LETTER U"
                  ,   "0076": "LATIN SMALL LETTER V"
                  ,   "0077": "LATIN SMALL LETTER W"
                  ,   "0078": "LATIN SMALL LETTER X"
                  ,   "0079": "LATIN SMALL LETTER Y"
                  ,   "007A": "LATIN SMALL LETTER Z"
                  ,   "007B": "LEFT CURLY BRACKET"
                  ,   "007C": "VERTICAL LINE"
                  ,   "007D": "RIGHT CURLY BRACKET"
                  ,   "007E": "TILDE" }
    ,   "CombDiaMk": {   "0300": "COMBINING GRAVE ACCENT"
                     ,   "0301": "COMBINING ACUTE ACCENT"
                     ,   "0302": "COMBINING CIRCUMFLEX ACCENT"
                     ,   "0303": "COMBINING TILDE"
                     ,   "0304": "COMBINING MACRON"
                     ,   "0305": "COMBINING OVERLINE"
                     ,   "0306": "COMBINING BREVE"
                     ,   "0307": "COMBINING DOT ABOVE"
                     ,   "0308": "COMBINING DIAERESIS"
                     ,   "0309": "COMBINING HOOK ABOVE"
                     ,   "030A": "COMBINING RING ABOVE"
                     ,   "030B": "COMBINING DOUBLE ACUTE ACCENT"
                     ,   "030D": "COMBINING VERTICAL LINE ABOVE"
                     ,   "030E": "COMBINING DOUBLE VERTICAL LINE ABOVE"
                     ,   "0315": "COMBINING COMMA ABOVE RIGHT"
                     ,   "0323": "COMBINING DOT BELOW"
                     ,   "0327": "COMBINING CEDILLA"
                     ,   "0328": "COMBINING OGONEK"
                     ,   "0332": "COMBINING LOW LINE"
                     ,   "0333": "COMBINING DOUBLE LOW LINE"
                     ,   "0336": "COMBINING LONG STROKE OVERLAY"
                     ,   "033E": "COMBINING VERTICAL TILDE"
                     ,   "033F": "COMBINING DOUBLE OVERLINE"
                     ,   "0359": "COMBINING ASTERISK BELOW"
                     ,   "035B": "COMBINING ZIGZAG ABOVE"
                     ,   "035C": "COMBINING DOUBLE BREVE BELOW"
                     ,   "0363": "COMBINING LATIN SMALL LETTER A"
                     ,   "0364": "COMBINING LATIN SMALL LETTER E"
                     ,   "0365": "COMBINING LATIN SMALL LETTER I"
                     ,   "0366": "COMBINING LATIN SMALL LETTER O"
                     ,   "0367": "COMBINING LATIN SMALL LETTER U"
                     ,   "0368": "COMBINING LATIN SMALL LETTER C"
                     ,   "0369": "COMBINING LATIN SMALL LETTER D"
                     ,   "036A": "COMBINING LATIN SMALL LETTER H"
                     ,   "036B": "COMBINING LATIN SMALL LETTER M"
                     ,   "036C": "COMBINING LATIN SMALL LETTER R"
                     ,   "036D": "COMBINING LATIN SMALL LETTER T"
                     ,   "036E": "COMBINING LATIN SMALL LETTER V"
                     ,   "036F": "COMBINING LATIN SMALL LETTER X" }
    ,   "CombDiaMkS": {   "1DCD": "COMBINING DOUBLE CIRCUMFLEX ABOVE"
                      ,   "1DCE": "COMBINING OGONEK ABOVE"
                      ,   "1DCF": "COMBINING ZIGZAG BELOW"
                      ,   "1DD0": "COMBINING IS BELOW"
                      ,   "1DD1": "COMBINING UR ABOVE"
                      ,   "1DD2": "COMBINING US ABOVE"
                      ,   "1DD3": "COMBINING LATIN SMALL LETTER FLATTENED OPEN A ABOVE"
                      ,   "1DD4": "COMBINING LATIN SMALL LETTER AE"
                      ,   "1DD5": "COMBINING LATIN SMALL LIGATURE AO"
                      ,   "1DD6": "COMBINING LATIN SMALL LIGATURE AV"
                      ,   "1DD7": "COMBINING LATIN SMALL LETTER C CEDILLA"
                      ,   "1DD8": "COMBINING LATIN LETTER INSULAR D"
                      ,   "1DD9": "COMBINING LATIN SMALL LETTER ETH"
                      ,   "1DDA": "COMBINING LATIN SMALL LETTER G"
                      ,   "1DDB": "COMBINING LATIN LETTER SMALL CAPITAL G"
                      ,   "1DDC": "COMBINING LATIN SMALL LETTER K"
                      ,   "1DDD": "COMBINING LATIN SMALL LETTER L"
                      ,   "1DDE": "COMBINING LATIN LETTER SMALL CAPITAL L"
                      ,   "1DDF": "COMBINING LATIN LETTER SMALL CAPITAL M"
                      ,   "1DE0": "COMBINING LATIN SMALL LETTER N"
                      ,   "1DE1": "COMBINING LATIN LETTER SMALL CAPITAL N"
                      ,   "1DE2": "COMBINING LATIN LETTER SMALL CAPITAL R"
                      ,   "1DE3": "COMBINING LATIN SMALL LETTER R ROTUNDA"
                      ,   "1DE4": "COMBINING LATIN SMALL LETTER S"
                      ,   "1DE5": "COMBINING LATIN SMALL LETTER LONG S"
                      ,   "1DE6": "COMBINING LATIN SMALL LETTER Z" }
    ,   "CurrSymb": { "20B0": "GERMAN PENNY SIGN" }
    ,   "Dingbats": {   "271D": "LATIN CROSS"
                    ,   "2766": "FLORAL HEART"
                    ,   "2767": "ROTATED FLORAL HEART BULLET" }
    ,   "GenPunct": {   "2000": "EN QUAD"
                    ,   "2001": "EM QUAD"
                    ,   "2010": "HYPHEN"
                    ,   "2011": "NON-BREAKING HYPHEN"
                    ,   "2012": "FIGURE DASH"
                    ,   "2013": "EN DASH"
                    ,   "2014": "EM DASH"
                    ,   "2015": "HORIZONTAL BAR"
                    ,   "2016": "DOUBLE VERTICAL LINE"
                    ,   "2018": "LEFT SINGLE QUOTATION MARK"
                    ,   "2019": "RIGHT SINGLE QUOTATION MARK"
                    ,   "201A": "SINGLE LOW-9 QUOTATION MARK"
                    ,   "201B": "SINGLE HIGH-REVERSED-9 QUOTATION MARK"
                    ,   "201C": "LEFT DOUBLE QUOTATION MARK"
                    ,   "201D": "RIGHT DOUBLE QUOTATION MARK"
                    ,   "201E": "DOUBLE LOW-9 QUOTATION MARK"
                    ,   "201F": "DOUBLE HIGH-REVERSED-9 QUOTATION MARK"
                    ,   "2020": "DAGGER"
                    ,   "2021": "DOUBLE DAGGER"
                    ,   "2022": "BULLET"
                    ,   "2023": "TRIANGULAR BULLET"
                    ,   "2024": "ONE DOT LEADER"
                    ,   "2025": "TWO DOT LEADER"
                    ,   "2027": "HYPHENATION POINT"
                    ,   "2030": "PER MILLE SIGN"
                    ,   "2032": "PRIME"
                    ,   "2033": "DOUBLE PRIME"
                    ,   "2039": "SINGLE LEFT-POINTING ANGLE QUOTATION MARK"
                    ,   "203A": "SINGLE RIGHT-POINTING ANGLE QUOTATION MARK"
                    ,   "203B": "REFERENCE MARK"
                    ,   "2042": "ASTERISM"
                    ,   "2044": "FRACTION SLASH"
                    ,   "2045": "LEFT SQUARE BRACKET WITH QUILL"
                    ,   "2046": "RIGHT SQUARE BRACKET WITH QUILL"
                    ,   "204A": "LATIN ABBREVIATION SIGN SMALL ET"
                    ,   "204B": "REVERSED PILCROW SIGN"
                    ,   "2058": "FOUR DOT PUNCTUATION"
                    ,   "205C": "DOTTED CROSS" }
    ,   "GeomShap": {   "25AA": "BLACK SMALL SQUARE"
                    ,   "25AB": "WHITE SMALL SQUARE"
                    ,   "25B9": "WHITE RIGHT-POINTING SMALL TRIANGLE"
                    ,   "25C3": "WHITE LEFT-POINTING SMALL TRIANGLE"
                    ,   "25CC": "DOTTED CIRCLE" }
    ,   "Georgian": { "10FB": "GEORGIAN PARAGRAPH SEPARATOR" }
    ,   "GkCo": {   "0398": "GREEK CAPITAL LETTER THETA"
                ,   "03B8": "GREEK SMALL LETTER THETA" }
    ,   "IPAExt": {   "0254": "LATIN SMALL LETTER OPEN O"
                  ,   "0256": "LATIN SMALL LETTER D WITH TAIL"
                  ,   "0259": "LATIN SMALL LETTER SCHWA"
                  ,   "025F": "LATIN SMALL LETTER DOTLESS J WITH STROKE"
                  ,   "0261": "LATIN SMALL LETTER SCRIPT G"
                  ,   "0262": "LATIN LETTER SMALL CAPITAL G"
                  ,   "0266": "LATIN SMALL LETTER H WITH HOOK"
                  ,   "0268": "LATIN SMALL LETTER I WITH STROKE"
                  ,   "026A": "LATIN LETTER SMALL CAPITAL I"
                  ,   "0272": "LATIN SMALL LETTER N WITH LEFT HOOK"
                  ,   "0274": "LATIN LETTER SMALL CAPITAL N"
                  ,   "0276": "LATIN LETTER SMALL CAPITAL OE"
                  ,   "027C": "LATIN SMALL LETTER R WITH LONG LEG"
                  ,   "0280": "LATIN LETTER SMALL CAPITAL R"
                  ,   "0289": "LATIN SMALL LETTER U BAR"
                  ,   "028F": "LATIN LETTER SMALL CAPITAL Y"
                  ,   "0292": "LATIN SMALL LETTER EZH"
                  ,   "0299": "LATIN LETTER SMALL CAPITAL B"
                  ,   "029C": "LATIN LETTER SMALL CAPITAL H"
                  ,   "029F": "LATIN LETTER SMALL CAPITAL L" }
    ,   "Lat1Suppl": {   "00A0": "NO-BREAK SPACE"
                     ,   "00A1": "INVERTED EXCLAMATION MARK"
                     ,   "00A2": "CENT SIGN"
                     ,   "00A3": "POUND SIGN"
                     ,   "00A4": "CURRENCY SIGN"
                     ,   "00A5": "YEN SIGN"
                     ,   "00A6": "BROKEN BAR"
                     ,   "00A7": "SECTION SIGN"
                     ,   "00A8": "DIAERESIS"
                     ,   "00A9": "COPYRIGHT SIGN"
                     ,   "00AA": "FEMININE ORDINAL INDICATOR"
                     ,   "00AB": "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK"
                     ,   "00AC": "NOT SIGN"
                     ,   "00AD": "SOFT HYPHEN"
                     ,   "00AE": "REGISTERED SIGN"
                     ,   "00B0": "DEGREE SIGN"
                     ,   "00B1": "PLUS-MINUS SIGN"
                     ,   "00B2": "SUPERSCRIPT TWO"
                     ,   "00B3": "SUPERSCRIPT THREE"
                     ,   "00B5": "MICRO SIGN"
                     ,   "00B6": "PILCROW SIGN"
                     ,   "00B7": "MIDDLE DOT"
                     ,   "00B9": "SUPERSCRIPT ONE"
                     ,   "00BA": "MASCULINE ORDINAL INDICATOR"
                     ,   "00BB": "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK"
                     ,   "00BC": "VULGAR FRACTION ONE QUARTER"
                     ,   "00BD": "VULGAR FRACTION ONE HALF"
                     ,   "00BE": "VULGAR FRACTION THREE QUARTERS"
                     ,   "00BF": "INVERTED QUESTION MARK"
                     ,   "00C0": "LATIN CAPITAL LETTER A WITH GRAVE"
                     ,   "00C1": "LATIN CAPITAL LETTER A WITH ACUTE"
                     ,   "00C2": "LATIN CAPITAL LETTER A WITH CIRCUMFLEX"
                     ,   "00C3": "LATIN CAPITAL LETTER A WITH TILDE"
                     ,   "00C4": "LATIN CAPITAL LETTER A WITH DIAERESIS"
                     ,   "00C5": "LATIN CAPITAL LETTER A WITH RING ABOVE"
                     ,   "00C6": "LATIN CAPITAL LETTER AE"
                     ,   "00C7": "LATIN CAPITAL LETTER C WITH CEDILLA"
                     ,   "00C8": "LATIN CAPITAL LETTER E WITH GRAVE"
                     ,   "00C9": "LATIN CAPITAL LETTER E WITH ACUTE"
                     ,   "00CA": "LATIN CAPITAL LETTER E WITH CIRCUMFLEX"
                     ,   "00CB": "LATIN CAPITAL LETTER E WITH DIAERESIS"
                     ,   "00CC": "LATIN CAPITAL LETTER I WITH GRAVE"
                     ,   "00CD": "LATIN CAPITAL LETTER I WITH ACUTE"
                     ,   "00CE": "LATIN CAPITAL LETTER I WITH CIRCUMFLEX"
                     ,   "00CF": "LATIN CAPITAL LETTER I WITH DIAERESIS"
                     ,   "00D0": "LATIN CAPITAL LETTER ETH"
                     ,   "00D1": "LATIN CAPITAL LETTER N WITH TILDE"
                     ,   "00D2": "LATIN CAPITAL LETTER O WITH GRAVE"
                     ,   "00D3": "LATIN CAPITAL LETTER O WITH ACUTE"
                     ,   "00D4": "LATIN CAPITAL LETTER O WITH CIRCUMFLEX"
                     ,   "00D5": "LATIN CAPITAL LETTER O WITH TILDE"
                     ,   "00D6": "LATIN CAPITAL LETTER O WITH DIAERESIS"
                     ,   "00D7": "MULTIPLICATION SIGN"
                     ,   "00D8": "LATIN CAPITAL LETTER O WITH STROKE"
                     ,   "00D9": "LATIN CAPITAL LETTER U WITH GRAVE"
                     ,   "00DA": "LATIN CAPITAL LETTER U WITH ACUTE"
                     ,   "00DB": "LATIN CAPITAL LETTER U WITH CIRCUMFLEX"
                     ,   "00DC": "LATIN CAPITAL LETTER U WITH DIAERESIS"
                     ,   "00DD": "LATIN CAPITAL LETTER Y WITH ACUTE"
                     ,   "00DE": "LATIN CAPITAL LETTER THORN"
                     ,   "00DF": "LATIN SMALL LETTER SHARP S"
                     ,   "00E0": "LATIN SMALL LETTER A WITH GRAVE"
                     ,   "00E1": "LATIN SMALL LETTER A WITH ACUTE"
                     ,   "00E2": "LATIN SMALL LETTER A WITH CIRCUMFLEX"
                     ,   "00E3": "LATIN SMALL LETTER A WITH TILDE"
                     ,   "00E4": "LATIN SMALL LETTER A WITH DIAERESIS"
                     ,   "00E5": "LATIN SMALL LETTER A WITH RING ABOVE"
                     ,   "00E6": "LATIN SMALL LETTER AE"
                     ,   "00E7": "LATIN SMALL LETTER C WITH CEDILLA"
                     ,   "00E8": "LATIN SMALL LETTER E WITH GRAVE"
                     ,   "00E9": "LATIN SMALL LETTER E WITH ACUTE"
                     ,   "00EA": "LATIN SMALL LETTER E WITH CIRCUMFLEX"
                     ,   "00EB": "LATIN SMALL LETTER E WITH DIAERESIS"
                     ,   "00EC": "LATIN SMALL LETTER I WITH GRAVE"
                     ,   "00ED": "LATIN SMALL LETTER I WITH ACUTE"
                     ,   "00EE": "LATIN SMALL LETTER I WITH CIRCUMFLEX"
                     ,   "00EF": "LATIN SMALL LETTER I WITH DIAERESIS"
                     ,   "00F0": "LATIN SMALL LETTER ETH"
                     ,   "00F1": "LATIN SMALL LETTER N WITH TILDE"
                     ,   "00F2": "LATIN SMALL LETTER O WITH GRAVE"
                     ,   "00F3": "LATIN SMALL LETTER O WITH ACUTE"
                     ,   "00F4": "LATIN SMALL LETTER O WITH CIRCUMFLEX"
                     ,   "00F5": "LATIN SMALL LETTER O WITH TILDE"
                     ,   "00F6": "LATIN SMALL LETTER O WITH DIAERESIS"
                     ,   "00F7": "DIVISION SIGN"
                     ,   "00F8": "LATIN SMALL LETTER O WITH STROKE"
                     ,   "00F9": "LATIN SMALL LETTER U WITH GRAVE"
                     ,   "00FA": "LATIN SMALL LETTER U WITH ACUTE"
                     ,   "00FB": "LATIN SMALL LETTER U WITH CIRCUMFLEX"
                     ,   "00FC": "LATIN SMALL LETTER U WITH DIAERESIS"
                     ,   "00FD": "LATIN SMALL LETTER Y WITH ACUTE"
                     ,   "00FE": "LATIN SMALL LETTER THORN"
                     ,   "00FF": "LATIN SMALL LETTER Y WITH DIAERESIS" }
    ,   "LatExtAdd": {   "1E02": "LATIN CAPITAL LETTER B WITH DOT ABOVE"
                     ,   "1E03": "LATIN SMALL LETTER B WITH DOT ABOVE"
                     ,   "1E04": "LATIN CAPITAL LETTER B WITH DOT BELOW"
                     ,   "1E05": "LATIN SMALL LETTER B WITH DOT BELOW"
                     ,   "1E0A": "LATIN CAPITAL LETTER D WITH DOT ABOVE"
                     ,   "1E0B": "LATIN SMALL LETTER D WITH DOT ABOVE"
                     ,   "1E0C": "LATIN CAPITAL LETTER D WITH DOT BELOW"
                     ,   "1E0D": "LATIN SMALL LETTER D WITH DOT BELOW"
                     ,   "1E16": "LATIN CAPITAL LETTER E WITH MACRON AND ACUTE"
                     ,   "1E17": "LATIN SMALL LETTER E WITH MACRON AND ACUTE"
                     ,   "1E1E": "LATIN CAPITAL LETTER F WITH DOT ABOVE"
                     ,   "1E1F": "LATIN SMALL LETTER F WITH DOT ABOVE"
                     ,   "1E22": "LATIN SMALL LETTER H WITH DOT ABOVE"
                     ,   "1E23": "LATIN CAPITAL LETTER H WITH DOT ABOVE"
                     ,   "1E24": "LATIN CAPITAL LETTER H WITH DOT BELOW"
                     ,   "1E25": "LATIN SMALL LETTER H WITH DOT BELOW"
                     ,   "1E30": "LATIN CAPITAL LETTER K WITH ACUTE"
                     ,   "1E31": "LATIN SMALL LETTER K WITH ACUTE"
                     ,   "1E32": "LATIN CAPITAL LETTER K WITH DOT BELOW"
                     ,   "1E33": "LATIN SMALL LETTER K WITH DOT BELOW"
                     ,   "1E36": "LATIN CAPITAL LETTER L WITH DOT BELOW"
                     ,   "1E37": "LATIN SMALL LETTER L WITH DOT BELOW"
                     ,   "1E3E": "LATIN CAPITAL LETTER M WITH ACUTE"
                     ,   "1E3F": "LATIN SMALL LETTER M WITH ACUTE"
                     ,   "1E40": "LATIN CAPITAL LETTER M WITH DOT ABOVE"
                     ,   "1E41": "LATIN SMALL LETTER M WITH DOT ABOVE"
                     ,   "1E42": "LATIN CAPITAL LETTER M WITH DOT BELOW"
                     ,   "1E43": "LATIN SMALL LETTER M WITH DOT BELOW"
                     ,   "1E44": "LATIN CAPITAL LETTER N WITH DOT ABOVE"
                     ,   "1E45": "LATIN SMALL LETTER N WITH DOT ABOVE"
                     ,   "1E46": "LATIN CAPITAL LETTER N WITH DOT BELOW"
                     ,   "1E47": "LATIN SMALL LETTER N WITH DOT BELOW"
                     ,   "1E52": "LATIN CAPITAL LETTER O WITH MACRON AND ACUTE"
                     ,   "1E53": "LATIN SMALL LETTER O WITH MACRON AND ACUTE"
                     ,   "1E54": "LATIN CAPITAL LETTER P WITH ACUTE"
                     ,   "1E55": "LATIN SMALL LETTER P WITH ACUTE"
                     ,   "1E56": "LATIN CAPITAL LETTER P WITH DOT ABOVE"
                     ,   "1E57": "LATIN SMALL LETTER P WITH DOT ABOVE"
                     ,   "1E58": "LATIN CAPITAL LETTER R WITH DOT ABOVE"
                     ,   "1E59": "LATIN SMALL LETTER R WITH DOT ABOVE"
                     ,   "1E5A": "LATIN CAPITAL LETTER R WITH DOT BELOW"
                     ,   "1E5B": "LATIN SMALL LETTER R WITH DOT BELOW"
                     ,   "1E60": "LATIN CAPITAL LETTER S WITH DOT ABOVE"
                     ,   "1E61": "LATIN SMALL LETTER S WITH DOT ABOVE"
                     ,   "1E62": "LATIN CAPITAL LETTER S WITH DOT BELOW"
                     ,   "1E63": "LATIN SMALL LETTER S WITH DOT BELOW"
                     ,   "1E6A": "LATIN CAPITAL LETTER T WITH DOT ABOVE"
                     ,   "1E6B": "LATIN SMALL LETTER T WITH DOT ABOVE"
                     ,   "1E6C": "LATIN CAPITAL LETTER T WITH DOT BELOW"
                     ,   "1E6D": "LATIN SMALL LETTER T WITH DOT BELOW"
                     ,   "1E7E": "LATIN CAPITAL LETTER V WITH DOT BELOW"
                     ,   "1E7F": "LATIN SMALL LETTER V WITH DOT BELOW"
                     ,   "1E80": "LATIN CAPITAL LETTER W WITH GRAVE"
                     ,   "1E81": "LATIN SMALL LETTER W WITH GRAVE"
                     ,   "1E82": "LATIN CAPITAL LETTER W WITH ACUTE"
                     ,   "1E83": "LATIN SMALL LETTER W WITH ACUTE"
                     ,   "1E84": "LATIN CAPITAL LETTER W WITH DIAERESIS"
                     ,   "1E85": "LATIN SMALL LETTER W WITH DIAERESIS"
                     ,   "1E86": "LATIN CAPITAL LETTER W WITH DOT ABOVE"
                     ,   "1E87": "LATIN SMALL LETTER W WITH DOT ABOVE"
                     ,   "1E88": "LATIN CAPITAL LETTER W WITH DOT BELOW"
                     ,   "1E89": "LATIN SMALL LETTER W WITH DOT BELOW"
                     ,   "1E8E": "LATIN CAPITAL LETTER Y WITH DOT ABOVE"
                     ,   "1E8F": "LATIN SMALL LETTER Y WITH DOT ABOVE"
                     ,   "1E92": "LATIN CAPITAL LETTER Z WITH DOT BELOW"
                     ,   "1E93": "LATIN SMALL LETTER Z WITH DOT BELOW"
                     ,   "1E98": "LATIN SMALL LETTER W WITH RING ABOVE"
                     ,   "1E99": "LATIN SMALL LETTER Y WITH RING ABOVE"
                     ,   "1E9C": "LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE"
                     ,   "1E9D": "LATIN SMALL LETTER LONG S WITH HIGH STROKE"
                     ,   "1E9E": "LATIN CAPITAL LETTER SHARP S"
                     ,   "1E9F": "LATIN SMALL LETTER DELTA"
                     ,   "1EA0": "LATIN CAPITAL LETTER A WITH DOT BELOW"
                     ,   "1EA1": "LATIN SMALL LETTER A WITH DOT BELOW"
                     ,   "1EA2": "LATIN CAPITAL LETTER A WITH HOOK ABOVE"
                     ,   "1EA3": "LATIN SMALL LETTER A WITH HOOK ABOVE"
                     ,   "1EAE": "LATIN CAPITAL LETTER A WITH BREVE AND ACUTE"
                     ,   "1EAF": "LATIN SMALL LETTER A WITH BREVE AND ACUTE"
                     ,   "1EB8": "LATIN CAPITAL LETTER E WITH DOT BELOW"
                     ,   "1EB9": "LATIN SMALL LETTER E WITH DOT BELOW"
                     ,   "1EC8": "LATIN CAPITAL LETTER I WITH HOOK ABOVE"
                     ,   "1EC9": "LATIN SMALL LETTER I WITH HOOK ABOVE"
                     ,   "1ECA": "LATIN CAPITAL LETTER I WITH DOT BELOW"
                     ,   "1ECB": "LATIN SMALL LETTER I WITH DOT BELOW"
                     ,   "1ECC": "LATIN CAPITAL LETTER O WITH DOT BELOW"
                     ,   "1ECD": "LATIN SMALL LETTER O WITH DOT BELOW"
                     ,   "1ECE": "LATIN CAPITAL LETTER O WITH HOOK ABOVE"
                     ,   "1ECF": "LATIN SMALL LETTER O WITH HOOK ABOVE"
                     ,   "1EE4": "LATIN CAPITAL LETTER U WITH DOT BELOW"
                     ,   "1EE5": "LATIN SMALL LETTER U WITH DOT BELOW"
                     ,   "1EE6": "LATIN CAPITAL LETTER U WITH HOOK ABOVE"
                     ,   "1EE7": "LATIN SMALL LETTER U WITH HOOK ABOVE"
                     ,   "1EF2": "LATIN CAPITAL LETTER Y WITH GRAVE"
                     ,   "1EF3": "LATIN SMALL LETTER Y WITH GRAVE"
                     ,   "1EF4": "LATIN CAPITAL LETTER Y WITH DOT BELOW"
                     ,   "1EF5": "LATIN SMALL LETTER Y WITH DOT BELOW"
                     ,   "1EF6": "LATIN CAPITAL LETTER Y WITH HOOK ABOVE"
                     ,   "1EF7": "LATIN SMALL LETTER Y WITH HOOK ABOVE"
                     ,   "1EFA": "LATIN CAPITAL LETTER MIDDLE-WELSH LL"
                     ,   "1EFB": "LATIN SMALL LETTER MIDDLE-WELSH LL"
                     ,   "1EFC": "LATIN CAPITAL LETTER MIDDLE-WELSH V"
                     ,   "1EFD": "LATIN SMALL LETTER MIDDLE-WELSH V"
                     ,   "1EFE": "LATIN CAPITAL LETTER Y WITH LOOP"
                     ,   "1EFF": "LATIN SMALL LETTER Y WITH LOOP" }
    ,   "LatExtA": {   "0100": "LATIN CAPITAL LETTER A WITH MACRON"
                   ,   "0101": "LATIN SMALL LETTER A WITH MACRON"
                   ,   "0102": "LATIN CAPITAL LETTER A WITH BREVE"
                   ,   "0103": "LATIN SMALL LETTER A WITH BREVE"
                   ,   "0104": "LATIN CAPITAL LETTER A WITH OGONEK"
                   ,   "0105": "LATIN SMALL LETTER A WITH OGONEK"
                   ,   "0106": "LATIN CAPITAL LETTER C WITH ACUTE"
                   ,   "0107": "LATIN SMALL LETTER C WITH ACUTE"
                   ,   "010A": "LATIN CAPITAL LETTER C WITH DOT ABOVE"
                   ,   "010B": "LATIN SMALL LETTER C WITH DOT ABOVE"
                   ,   "0110": "LATIN CAPITAL LETTER D WITH STROKE"
                   ,   "0111": "LATIN SMALL LETTER D WITH STROKE"
                   ,   "0112": "LATIN CAPITAL LETTER E WITH MACRON"
                   ,   "0113": "LATIN SMALL LETTER E WITH MACRON"
                   ,   "0114": "LATIN CAPITAL LETTER E WITH BREVE"
                   ,   "0115": "LATIN SMALL LETTER E WITH BREVE"
                   ,   "0116": "LATIN CAPITAL LETTER E WITH DOT ABOVE"
                   ,   "0117": "LATIN SMALL LETTER E WITH DOT ABOVE"
                   ,   "0118": "LATIN CAPITAL LETTER E WITH OGONEK"
                   ,   "0119": "LATIN SMALL LETTER E WITH OGONEK"
                   ,   "0120": "LATIN CAPITAL LETTER G WITH DOT ABOVE"
                   ,   "0121": "LATIN SMALL LETTER G WITH DOT ABOVE"
                   ,   "0127": "LATIN SMALL LETTER H WITH STROKE"
                   ,   "012A": "LATIN CAPITAL LETTER I WITH MACRON"
                   ,   "012B": "LATIN SMALL LETTER I WITH MACRON"
                   ,   "012C": "LATIN CAPITAL LETTER I WITH BREVE"
                   ,   "012D": "LATIN SMALL LETTER I WITH BREVE"
                   ,   "012E": "LATIN CAPITAL LETTER I WITH OGONEK"
                   ,   "012F": "LATIN SMALL LETTER I WITH OGONEK"
                   ,   "0130": "LATIN CAPITAL LETTER I WITH DOT ABOVE"
                   ,   "0131": "LATIN SMALL LETTER DOTLESS I"
                   ,   "0132": "LATIN CAPITAL LIGATURE IJ"
                   ,   "0133": "LATIN SMALL LIGATURE IJ"
                   ,   "0139": "LATIN CAPITAL LETTER L WITH ACUTE"
                   ,   "013A": "LATIN SMALL LETTER L WITH ACUTE"
                   ,   "0141": "LATIN CAPITAL LETTER L WITH STROKE"
                   ,   "0142": "LATIN SMALL LETTER L WITH STROKE"
                   ,   "0143": "LATIN CAPITAL LETTER N WITH ACUTE"
                   ,   "0144": "LATIN SMALL LETTER N WITH ACUTE"
                   ,   "014A": "LATIN CAPITAL LETTER ENG"
                   ,   "014B": "LATIN SMALL LETTER ENG"
                   ,   "014C": "LATIN CAPITAL LETTER O WITH MACRON"
                   ,   "014D": "LATIN SMALL LETTER O WITH MACRON"
                   ,   "014E": "LATIN CAPITAL LETTER O WITH BREVE"
                   ,   "014F": "LATIN SMALL LETTER O WITH BREVE"
                   ,   "0150": "LATIN CAPITAL LETTER O WITH DOUBLE ACUTE"
                   ,   "0151": "LATIN SMALL LETTER O WITH DOUBLE ACUTE"
                   ,   "0152": "LATIN CAPITAL LIGATURE OE"
                   ,   "0153": "LATIN SMALL LIGATURE OE"
                   ,   "0154": "LATIN CAPITAL LETTER R WITH ACUTE"
                   ,   "0155": "LATIN SMALL LETTER R WITH ACUTE"
                   ,   "015A": "LATIN CAPITAL LETTER S WITH ACUTE"
                   ,   "015B": "LATIN SMALL LETTER S WITH ACUTE"
                   ,   "016A": "LATIN CAPITAL LETTER U WITH MACRON"
                   ,   "016B": "LATIN SMALL LETTER U WITH MACRON"
                   ,   "016C": "LATIN CAPITAL LETTER U WITH BREVE"
                   ,   "016D": "LATIN SMALL LETTER U WITH BREVE"
                   ,   "016E": "LATIN CAPITAL LETTER U WITH RING ABOVE"
                   ,   "016F": "LATIN SMALL LETTER U WITH RING ABOVE"
                   ,   "0170": "LATIN CAPITAL LETTER U WITH DOUBLE ACUTE"
                   ,   "0171": "LATIN SMALL LETTER U WITH DOUBLE ACUTE"
                   ,   "0172": "LATIN CAPITAL LETTER U WITH OGONEK"
                   ,   "0173": "LATIN SMALL LETTER U WITH OGONEK"
                   ,   "0174": "LATIN CAPITAL LETTER W WITH CIRCUMFLEX"
                   ,   "0175": "LATIN SMALL LETTER W WITH CIRCUMFLEX"
                   ,   "0176": "LATIN CAPITAL LETTER Y WITH CIRCUMFLEX"
                   ,   "0177": "LATIN SMALL LETTER Y WITH CIRCUMFLEX"
                   ,   "0178": "LATIN CAPITAL LETTER Y WITH DIAERESIS"
                   ,   "017B": "LATIN CAPITAL LETTER Z WITH DOT ABOVE"
                   ,   "017C": "LATIN SMALL LETTER Z WITH DOT ABOVE"
                   ,   "017F": "LATIN SMALL LETTER LONG S" }
    ,   "LatExtB": {   "0180": "LATIN SMALL LETTER B WITH STROKE"
                   ,   "0195": "LATIN SMALL LETTER HV"
                   ,   "0199": "LATIN SMALL LETTER K WITH HOOK"
                   ,   "019A": "LATIN SMALL LETTER L WITH BAR"
                   ,   "019E": "LATIN SMALL LETTER N WITH LONG RIGHT LEG"
                   ,   "01A6": "LATIN LETTER YR"
                   ,   "01B5": "LATIN CAPITAL LETTER Z WITH STROKE"
                   ,   "01B6": "LATIN SMALL LETTER Z WITH STROKE"
                   ,   "01B7": "LATIN CAPITAL LETTER EZH"
                   ,   "01BF": "LATIN LETTER WYNN"
                   ,   "01D1": "LATIN CAPITAL LETTER O WITH CARON"
                   ,   "01D2": "LATIN SMALL LETTER O WITH CARON"
                   ,   "01D3": "LATIN CAPITAL LETTER U WITH CARON"
                   ,   "01D4": "LATIN SMALL LETTER U WITH CARON"
                   ,   "01D5": "LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON"
                   ,   "01D6": "LATIN SMALL LETTER U WITH DIAERESIS AND MACRON"
                   ,   "01E2": "LATIN CAPITAL LETTER AE WITH MACRON"
                   ,   "01E3": "LATIN SMALL LETTER AE WITH MACRON"
                   ,   "01E4": "LATIN CAPITAL LETTER G WITH STROKE"
                   ,   "01E5": "LATIN SMALL LETTER G WITH STROKE"
                   ,   "01EA": "LATIN CAPITAL LETTER O WITH OGONEK"
                   ,   "01EB": "LATIN SMALL LETTER O WITH OGONEK"
                   ,   "01EC": "LATIN CAPITAL LETTER O WITH OGONEK AND MACRON"
                   ,   "01ED": "LATIN SMALL LETTER O WITH OGONEK AND MACRON"
                   ,   "01F4": "LATIN CAPITAL LETTER G WITH ACUTE"
                   ,   "01F5": "LATIN SMALL LETTER G WITH ACUTE"
                   ,   "01F6": "LATIN CAPITAL LETTER HWAIR"
                   ,   "01F7": "LATIN CAPITAL LETTER WYNN"
                   ,   "01FC": "LATIN CAPITAL LETTER AE WITH ACUTE"
                   ,   "01FD": "LATIN SMALL LETTER AE WITH ACUTE"
                   ,   "01FE": "LATIN CAPITAL LETTER O WITH STROKE AND ACUTE"
                   ,   "01FF": "LATIN SMALL LETTER O WITH STROKE AND ACUTE"
                   ,   "021C": "LATIN CAPITAL LETTER YOGH"
                   ,   "021D": "LATIN SMALL LETTER YOGH"
                   ,   "0226": "LATIN CAPITAL LETTER A WITH DOT ABOVE"
                   ,   "0227": "LATIN SMALL LETTER A WITH DOT ABOVE"
                   ,   "022A": "LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON"
                   ,   "022B": "LATIN SMALL LETTER O WITH DIAERESIS AND MACRON"
                   ,   "022E": "LATIN CAPITAL LETTER O WITH DOT ABOVE"
                   ,   "022F": "LATIN SMALL LETTER O WITH DOT ABOVE"
                   ,   "0232": "LATIN CAPITAL LETTER Y WITH MACRON"
                   ,   "0233": "LATIN SMALL LETTER Y WITH MACRON"
                   ,   "0237": "LATIN SMALL LETTER DOTLESS J"
                   ,   "0248": "LATIN CAPITAL LETTER J WITH STROKE"
                   ,   "0249": "LATIN SMALL LETTER J WITH STROKE" }
    ,   "LatExtC": {   "2C75": "LATIN CAPITAL LETTER HALF H"
                   ,   "2C76": "LATIN SMALL LETTER HALF H" }
    ,   "LatExtD": {   "A730": "LATIN LETTER SMALL CAPITAL F"
                   ,   "A731": "LATIN LETTER SMALL CAPITAL S"
                   ,   "A732": "LATIN CAPITAL LETTER AA"
                   ,   "A733": "LATIN SMALL LETTER AA"
                   ,   "A734": "LATIN CAPITAL LETTER AO"
                   ,   "A735": "LATIN SMALL LETTER AO"
                   ,   "A736": "LATIN CAPITAL LETTER AU"
                   ,   "A737": "LATIN SMALL LETTER AU"
                   ,   "A738": "LATIN CAPITAL LETTER AV"
                   ,   "A739": "LATIN SMALL LETTER AV"
                   ,   "A73A": "LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR"
                   ,   "A73B": "LATIN SMALL LETTER AV WITH HORIZONTAL BAR"
                   ,   "A73C": "LATIN CAPITAL LETTER AY"
                   ,   "A73D": "LATIN SMALL LETTER AY"
                   ,   "A73E": "LATIN CAPITAL LETTER REVERSED C WITH DOT"
                   ,   "A73F": "LATIN SMALL LETTER REVERSED C WITH DOT"
                   ,   "A740": "LATIN CAPITAL LETTER K WITH STROKE"
                   ,   "A741": "LATIN SMALL LETTER K WITH STROKE"
                   ,   "A742": "LATIN CAPITAL LETTER K WITH DIAGONAL STROKE"
                   ,   "A743": "LATIN SMALL LETTER K WITH DIAGONAL STROKE"
                   ,   "A744": "LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE"
                   ,   "A745": "LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE"
                   ,   "A746": "LATIN CAPITAL LETTER BROKEN L"
                   ,   "A747": "LATIN SMALL LETTER BROKEN L"
                   ,   "A748": "LATIN CAPITAL LETTER L WITH HIGH STROKE"
                   ,   "A749": "LATIN SMALL LETTER L WITH HIGH STROKE"
                   ,   "A74A": "LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY"
                   ,   "A74B": "LATIN SMALL LETTER O WITH LONG STROKE OVERLAY"
                   ,   "A74C": "LATIN SMALL LETTER OE WITH LOOP"
                   ,   "A74D": "LATIN CAPITAL LETTER OE WITH LOOP"
                   ,   "A74E": "LATIN CAPITAL LETTER OO"
                   ,   "A74F": "LATIN SMALL LETTER OO"
                   ,   "A750": "LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER"
                   ,   "A751": "LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER"
                   ,   "A752": "LATIN CAPITAL LETTER P WITH FLOURISH"
                   ,   "A753": "LATIN SMALL LETTER P WITH FLOURISH"
                   ,   "A754": "LATIN CAPITAL LETTER P WITH SQUIRREL TAIL"
                   ,   "A755": "LATIN SMALL LETTER P WITH SQUIRREL TAIL"
                   ,   "A756": "LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER"
                   ,   "A757": "LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER"
                   ,   "A758": "LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE"
                   ,   "A759": "LATIN SMALL LETTER Q WITH DIAGONAL STROKE"
                   ,   "A75A": "LATIN CAPITAL LETTER R ROTUNDA"
                   ,   "A75B": "LATIN SMALL LETTER R ROTUNDA"
                   ,   "A75C": "LATIN CAPITAL LETTER RUM ROTUNDA"
                   ,   "A75D": "LATIN SMALL LETTER RUM ROTUNDA"
                   ,   "A75E": "LATIN CAPITAL LETTER V WITH DIAGONAL STROKE"
                   ,   "A75F": "LATIN SMALL LETTER V WITH DIAGONAL STROKE"
                   ,   "A760": "LATIN CAPITAL LETTER VY"
                   ,   "A761": "LATIN SMALL LETTER VY"
                   ,   "A762": "LATIN CAPITAL LETTER VISIGOTHIC Z"
                   ,   "A763": "LATIN SMALL LETTER VISIGOTHIC Z"
                   ,   "A764": "LATIN CAPITAL LETTER THORN WITH STROKE"
                   ,   "A765": "LATIN SMALL LETTER THORN WITH STROKE"
                   ,   "A766": "LATIN CAPITAL LETTER THORN WITH STROKE THROUGH DESCENDER"
                   ,   "A767": "LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER"
                   ,   "A768": "LATIN CAPITAL LETTER VEND"
                   ,   "A769": "LATIN SMALL LETTER VEND"
                   ,   "A76A": "LATIN CAPITAL LETTER ET"
                   ,   "A76B": "LATIN SMALL LETTER ET"
                   ,   "A76C": "LATIN CAPITAL LETTER IS"
                   ,   "A76D": "LATIN SMALL LETTER IS"
                   ,   "A76E": "LATIN CAPITAL LETTER CON"
                   ,   "A76F": "LATIN SMALL LETTER CON"
                   ,   "A770": "MODIFIER LETTER US"
                   ,   "A771": "LATIN SMALL LETTER DUM"
                   ,   "A772": "LATIN SMALL LETTER LUM"
                   ,   "A773": "LATIN SMALL LETTER MUM"
                   ,   "A774": "LATIN SMALL LETTER NUM"
                   ,   "A775": "LATIN SMALL LETTER RUM"
                   ,   "A776": "LATIN LETTER SMALL CAPITAL RUM"
                   ,   "A777": "LATIN SMALL LETTER TUM"
                   ,   "A778": "LATIN SMALL LETTER UM"
                   ,   "A779": "LATIN CAPITAL LETTER INSULAR D"
                   ,   "A77A": "LATIN SMALL LETTER INSULAR D"
                   ,   "A77B": "LATIN CAPITAL LETTER INSULAR F"
                   ,   "A77C": "LATIN SMALL LETTER INSULAR F"
                   ,   "A77D": "LATIN CAPITAL LETTER INSULAR G"
                   ,   "A77E": "LATIN CAPITAL LETTER TURNED INSULAR G"
                   ,   "A77F": "LATIN SMALL LETTER TURNED INSULAR G"
                   ,   "A780": "LATIN CAPITAL LETTER TURNED L"
                   ,   "A781": "LATIN SMALL LETTER TURNED L"
                   ,   "A782": "LATIN CAPITAL LETTER INSULAR R"
                   ,   "A783": "LATIN SMALL LETTER INSULAR R"
                   ,   "A784": "LATIN CAPITAL LETTER INSULAR S"
                   ,   "A785": "LATIN SMALL LETTER INSULAR S"
                   ,   "A786": "LATIN CAPITAL LETTER INSULAR T"
                   ,   "A787": "LATIN SMALL LETTER INSULAR T"
                   ,   "A7FB": "LATIN EPIGRAPHIC LETTER REVERSED F"
                   ,   "A7FC": "LATIN EPIGRAPHIC LETTER REVERSED P"
                   ,   "A7FD": "LATIN EPIGRAPHIC LETTER INVERTED M"
                   ,   "A7FE": "LATIN EPIGRAPHIC LETTER I LONGA"
                   ,   "A7FF": "LATIN EPIGRAPHIC LETTER ARCHAIC M" }
    ,   "LettSymb": {   "2108": "SCRUPLE"
                    ,   "2114": "L B BAR SYMBOL"
                    ,   "211E": "PRESCRIPTION TAKE"
                    ,   "211F": "RESPONSE"
                    ,   "2123": "VERSICLE"
                    ,   "2125": "OUNCE SIGN"
                    ,   "2132": "TURNED CAPITAL F"
                    ,   "214E": "TURNED SMALL F" }
    ,   "MathOp": {   "2212": "MINUS"
                  ,   "221E": "INFINITY"
                  ,   "2227": "LOGICAL AND"
                  ,   "2234": "THEREFORE"
                  ,   "2235": "BECAUSE"
                  ,   "2237": "PROPORTION"
                  ,   "223B": "HOMOTHETIC"
                  ,   "2248": "ALMOST EQUAL TO"
                  ,   "2260": "NOT EQUAL TO"
                  ,   "22D7": "GREATER-THAN WITH DOT" }
    ,   "MiMaSymbA": {   "27E6": "LEFT WHITE SQUARE BRACKET"
                     ,   "27E7": "RIGHT WHITE SQUARE BRACKET"
                     ,   "27E8": "LEFT ANGLE BRACKET"
                     ,   "27E9": "RIGHT ANGLE BRACKET" }
    ,   "MiscTech": {   "23D1": "METRICAL BREVE"
                    ,   "23D2": "METRICAL LONG OVER SHORT"
                    ,   "23D3": "METRICAL SHORT OVER LONG"
                    ,   "23D4": "METRICAL LONG OVER TWO SHORTS" }
    ,   "NumbFo": {   "2180": "ROMAN NUMERAL ONE THOUSAND C D"
                  ,   "2181": "ROMAN NUMERAL FIVE THOUSAND"
                  ,   "2182": "ROMAN NUMERAL TEN THOUSAND"
                  ,   "2183": "ROMAN NUMERAL REVERSED ONE HUNDRED"
                  ,   "2184": "LATIN ABBREVIATION SIGN SMALL CON" }
    ,   "PhonExt": {   "1D00": "LATIN LETTER SMALL CAPITAL A"
                   ,   "1D01": "LATIN LETTER SMALL CAPITAL AE"
                   ,   "1D04": "LATIN LETTER SMALL CAPITAL C"
                   ,   "1D05": "LATIN LETTER SMALL CAPITAL D"
                   ,   "1D06": "LATIN LETTER SMALL CAPITAL ETH"
                   ,   "1D07": "LATIN LETTER SMALL CAPITAL E"
                   ,   "1D0A": "LATIN LETTER SMALL CAPITAL J"
                   ,   "1D0B": "LATIN LETTER SMALL CAPITAL K"
                   ,   "1D0D": "LATIN LETTER SMALL CAPITAL M"
                   ,   "1D0F": "LATIN LETTER SMALL CAPITAL O"
                   ,   "1D18": "LATIN LETTER SMALL CAPITAL P"
                   ,   "1D1B": "LATIN LETTER SMALL CAPITAL T"
                   ,   "1D1C": "LATIN LETTER SMALL CAPITAL U"
                   ,   "1D20": "LATIN LETTER SMALL CAPITAL V"
                   ,   "1D21": "LATIN LETTER SMALL CAPITAL W"
                   ,   "1D22": "LATIN LETTER SMALL CAPITAL Z"
                   ,   "1D35": "MODIFIER CAPITAL LETTER I"
                   ,   "1D79": "LATIN SMALL LETTER INSULAR G" }
    ,   "Run": {   "16A0": "RUNIC LETTER FEHU FEOH FE F"
               ,   "16A1": "RUNIC LETTER V"
               ,   "16A2": "RUNIC LETTER URUZ UR U"
               ,   "16A3": "RUNIC LETTER YR"
               ,   "16A4": "RUNIC LETTER Y"
               ,   "16A5": "RUNIC LETTER W"
               ,   "16A6": "RUNIC LETTER THURISAZ THURS THORN"
               ,   "16A7": "RUNIC LETTER ETH"
               ,   "16A8": "RUNIC LETTER ANSUZ A"
               ,   "16D8": "RUNIC MEDIEVAL LETTER M" }
    ,   "SpModLet": {   "02BC": "MODIFIER LETTER APOSTROPHE"
                    ,   "02C8": "MODIFIER LETTER VERTICAL LINE"
                    ,   "02D8": "BREVE"
                    ,   "02D9": "DOT ABOVE"
                    ,   "02DA": "RING ABOVE"
                    ,   "02DB": "OGONEK"
                    ,   "02DC": "SMALL TILDE"
                    ,   "02DD": "DOUBLE ACUTE ACCENT"
                    ,   "02E3": "MODIFIER LETTER SMALL X" }
    ,   "SupplMathOp": { "2AFD": "PUNCTUATION MARK DOUBLE SOLIDUS" }
    ,   "SupplPunct": {   "2E0C": "LEFT UPPER SLANTED STROKE"
                      ,   "2E0D": "RIGHT UPPER SLANTED STROKE"
                      ,   "2E17": "DOUBLE OBLIQUE HYPHEN"
                      ,   "2E1C": "RIGHT LOWER SLANTED STROKE"
                      ,   "2E1D": "LEFT LOWER SLANTED STROKE"
                      ,   "2E20": "RIGHT VERTICAL BAR WITH QUILL"
                      ,   "2E21": "LEFT VERTICAL BAR WITH QUILL"
                      ,   "2E22": "TOP LEFT HALF BRACKET"
                      ,   "2E23": "TOP RIGHT HALF BRACKET"
                      ,   "2E24": "BOTTOM LEFT HALF BRACKET"
                      ,   "2E25": "BOTTOM RIGHT HALF BRACKET"
                      ,   "2E26": "LEFT SIDEWAYS U BRACKET"
                      ,   "2E27": "RIGHT SIDEWAYS U BRACKET"
                      ,   "2E28": "LEFT DOUBLE PARENTHESIS"
                      ,   "2E29": "RIGHT DOUBLE PARENTHESIS"
                      ,   "2E2A": "TWO DOTS OVER ONE DOT PUNCTUATION"
                      ,   "2E2B": "ONE DOT OVER TWO DOTS PUNCTUATION"
                      ,   "2E2C": "FOUR DOTS PUNCTUATION"
                      ,   "2E2D": "FIVE DOT MARK"
                      ,   "2E2E": "REVERSED QUESTION MARK" }
    ,   "SupSub": {   "2070": "SUPERSCRIPT ZERO"
                  ,   "2074": "SUPERSCRIPT FOUR"
                  ,   "2075": "SUPERSCRIPT FIVE"
                  ,   "2076": "SUPERSCRIPT SIX"
                  ,   "2077": "SUPERSCRIPT SEVEN"
                  ,   "2078": "SUPERSCRIPT EIGHT"
                  ,   "2079": "SUPERSCRIPT NINE"
                  ,   "2080": "SUBSCRIPT ZERO"
                  ,   "2081": "SUBSCRIPT ONE"
                  ,   "2082": "SUBSCRIPT TWO"
                  ,   "2083": "SUBSCRIPT THREE"
                  ,   "2084": "SUBSCRIPT FOUR"
                  ,   "2085": "SUBSCRIPT FIVE"
                  ,   "2086": "SUBSCRIPT SIX"
                  ,   "2087": "SUBSCRIPT SEVEN"
                  ,   "2088": "SUBSCRIPT EIGHT"
                  ,   "2089": "SUBSCRIPT NINE" }
    };
});
